### ISSUE TITLE
TinyAuth

### ISSUE THREAD

**Issue by dlimitbreaker** [dereuromark/cakephp-tinyauth#10]
after set, on running the project i got this error message: Authorization adapter "TinyAuth.Tiny" was not found. I need help on this.

**Comment by dereuromark** [comment]
Please be more specific on how to reproduce, what is the exact setup/config etc.

**Comment by dlimitbreaker** [comment]
here is my Appcontroller part for the plugin:
            'authorize' => [
            'TinyAuth.Tiny' => [
                'allowUser' => false,
                'authorizeByPrefix' => false,
                'prefixes' => [],
                'superAdminRole' => null,
                'rolesTable'=>'Roles',
                'roleColumn' => 'roles_id'
            ]
        ]

i have already loaded the plugin and configured the acl.ini file and i'm not sure if there is any other thing i need to do that i have not done but when i executed my project i got the error message i posted earlier.

**Comment by dereuromark** [comment]
Did you properly load the plugin and stuff? I am sure you missed some part of the installation process that is documented.

**Comment by dlimitbreaker** [comment]
i did. the plugin is in a folder bearing your name. but is my setup above correct?

**Comment by dereuromark** [comment]
The setup might, but your plugin is not properly loaded as per https://github.com/dereuromark/cakephp-tinyauth#how-to-include
