### ISSUE TITLE
Router Scope Issue

### ISSUE THREAD

**Issue by spacebiscuit** [dereuromark/cakephp-tinyauth#102]
I have a controller with the following namespace:

`namespace App\Controller\Api\Datatables;`

The controller is Listings and my function is Filter

I have the follwing route setup:

```
Router::scope('/datatables', ['prefix' => 'api/datatables'], function (RouteBuilder $routes) {
    $routes->extensions(['json', 'xml', 'ajax']);   
    $routes->fallbacks(DashedRoute::class);
});
```

This allows me to call the following url:

/datatables/listings/filter.json

I want to allow the filter function:

`datatables/Listings = filter`

When I call my URL I am re-directed to login. If I login the url works, so the allow_auth works.

I have also tried the following:

api/datatables/Listings = filter
api/Datatables/Listings = filter
Api/Datatables/Listings = filter
api/datatables/Listings = filter
datatables/Listings = filter
Datatables/Listings = filter
api/Listings = filter

No matter what the path is not allowed. If I move the controller to the default location then in allow_auth:

Listings = filter

the filter function is accessible without authorisation. This suggests that there is a problem with the plugin when user a router scope.

**Comment by dereuromark** [comment]
Some of the discussion is also at [SO](https://stackoverflow.com/questions/56502019/cakephp3-tiny-auth-allow-auth-fail).

Please post the Routing array here inside $this->request->params for this specific URL.
That will be important to know for what is needed in this specific case.

**Comment by dereuromark** [comment]
calling `/api/datatables/listings/filter.json`:
```php
    'controller' => 'Listings',
    'action' => 'filter',
    'pass' => [],
    'prefix' => 'api/datatables',
    'plugin' => null,
    '_ext' => 'json',
    '_matchedRoute' => '/datatables/:controller/:action/*',
    '?' => [
        'string' => 'seat'
    ]
```

**Comment by dereuromark** [comment]
PR open - waiting for confirmation.
