### ISSUE TITLE
How can I set the "unauthorized" notification message?

### ISSUE THREAD

**Issue by adam-je** [dereuromark/cakephp-tinyauth#11]
Similar to the one in AppController.php. initialize() method:
'authError' => 'That action reguires you to login first',

**Comment by dereuromark** [comment]
?
the message is part of the component afaik, not the auth adapters.

**Comment by adam-je** [comment]
Thanks for the quick response @dereuromark. I'm aware that the Flash message is a CakePHP component, but my auth just redirects the user back to their previous location without telling them that they can't access the particular action they just attempted. 

So I just need it to say something after redirecting, any ideas?

**Comment by dereuromark** [comment]
Must be part of the documented redirect error messages, please check the docs.
http://book.cakephp.org/3.0/en/controllers/components/authentication.html#configuration-options
authError I assume
