### ISSUE TITLE
Cake4 - Documentation suggestions

### ISSUE THREAD

**Issue by davidyell** [dereuromark/cakephp-tinyauth#114]
### https://github.com/dereuromark/cakephp-tinyauth/blob/cake4/README.md

Just personal preference, but I tend to put installation instructions at the top of the readme, after a brief introduction about what problem the plugin solves. It took me a bit of searching to find the installation instructions at the bottom of the readme.

### https://github.com/dereuromark/cakephp-tinyauth/blob/cake4/docs/AuthPanel.md

I think it would be handy to include a link to the relevant section of the DebugKit documentation on how to add panels. As saying to add it to configuration but not showing where or how is confusing and a bit frustrating.

Once I implemented the `TinyAuth.Auth` component I still didn't see a DebugKit panel show up. I configured the panel using `Configure::write('DebutKit.panels', ['TinyAuth.Auth' => true]);`

### https://github.com/dereuromark/cakephp-tinyauth/blob/cake4/docs/README.md

I would move the DebugKit panel documentation after the Authentication, Authorization and Configuration sections. As I've enabled the panel first, but because I haven't yet enabled the other parts, it doesn't show up in DebugKit Toolbar. Could be my bad implementation.

### https://github.com/dereuromark/cakephp-tinyauth/blob/cake4/docs/Authentication.md

I'd want to know how to enable it before trying to configure it. So I would personally move the enable section to the top of the readme here.

There is no documentation which shows how to configure the components options. My application is using `email_address` as the username field. So when I loaded the component I wasn't able to login. I guessed that it follows the same configuration options as the core AuthComponent which worked, so I'd add a link stating that into the docs.

I also couldn't seem to get the `finder` option to work. As I have a scoped find using `is_active`. If the component doesn't support custom finders this should be noted in the docs.

**Comment by dereuromark** [comment]
> AuthPanel.md

How would that doc addition look like?


> I would move the DebugKit panel documentation after 

Sounds good

> so I'd add a link stating that into the docs.

Are you able to PR this?

> I also couldn't seem to get the finder option to work.

I only know this from AuthComponent (old way), how does this work in the new 4.x way?

**Comment by davidyell** [comment]
I would envisage the DebugKit panel linking to the configuration documentation.
https://book.cakephp.org/debugkit/3/en/index.html#configuration
Although as I didn't manage to get it working, I'm not sure if those docs still apply to the 4.x-dev branch of DebugKit.

I haven't yet tried the new Auth plugins, so am not too sure how that would work unfortunately.

I'll submit a PR for the link

**Comment by davidyell** [comment]
I had a quick look at the core AuthComponent, and it's deprecated in favour of the new Auth plugins. So I won't submit a PR to link to the documentation for the AuthComponent, as if you're targeting Cake 4, showing deprecated configuration might not be ideal.

If it's okay, I'll leave that up to you as I can see that it might involve changes to the TinyAuthComponent which would be your choice.
