### ISSUE TITLE
Missing TinyAuth role id field (Auth.User.user_role) in user session (CakePHP 4)

### ISSUE THREAD

**Issue by hassifmohd** [dereuromark/cakephp-tinyauth#116]
## Error

i receive an error
```
Missing TinyAuth role id field (Auth.User.user_role) in the user session
```

This error comes from this line [here](https://github.com/dereuromark/cakephp-tinyauth/blob/3.0.0/src/Auth/AclTrait.php#L515)

## Investigation

Because of this line [here](https://github.com/dereuromark/cakephp-tinyauth/blob/3.0.0/src/Policy/RequestPolicy.php#L44)

What actually happens is converting `$identity->getOriginalData()` into array got problem

Example of the problem
```
$user = $identity ? (array) $identity->getOriginalData() : [];
$userObject = $identity->getOriginalData();
dump($userObject->user_role); //return 1
dump($user['user_role']); //return Undefined index: user_role
```

below solution solve the issue
```
//at function canAccess(...)
$user = $identity ? $this->toArrayV2($identity->getOriginalData()) : [];

public function toArrayV2($object)
{
    return json_decode(json_encode($object), true);
}
```

## Others

versions
```
"cakephp/authentication": "^2.0",
"cakephp/authorization": "^2.0",
"cakephp/cakephp": "^4.0",
"dereuromark/cakephp-tinyauth": "3.0.0",
```

**Comment by dereuromark** [comment]
So you are storing an object in the session?
Is that new in cake4 apps - or just your app?
I always (still) use array, as object is an anti pattern here for session storage.

**Comment by dereuromark** [comment]
You can make a PR with your suggested changes if that helps to solve this.
if (is_object) { ...}
Then we can use your solution here.

**Comment by hassifmohd** [comment]
> So you are storing an object in the session?
Is that new in cake4 apps - or just your app?

in my case, it was an Entity Object

I cannot double confirm `$identity->getOriginalData()` will return Object or Array because i need some time to setup new cakephp enviroment

**Comment by hassifmohd** [comment]
i am unable to figure out why my `$identity->getOriginalData()`

```
//app/vendor/cakephp/authorization/src/IdentityInterface.php
* @return array|\ArrayAccess
     */
    public function getOriginalData(); <-- it is indeed should return an array
```

---

anyway, since my data is an Entity I had create custom RequestPolicy and `$identity->getOriginalData()->toArray()` will solve my problem

---

i am closing this issue because i cannot prove it was an issue. sorry
