### ISSUE TITLE
Cake 3.x Auth component mentioned in docs

### ISSUE THREAD

**Issue by othercorey** [dereuromark/cakephp-tinyauth#119]
The Authorization doc for the cake 4.x version links to the 3.x Auth component documentation.

https://github.com/dereuromark/cakephp-tinyauth/blob/master/docs/Authorization.md#enabling

Is any part of that section still relevant or should be removed?

**Comment by dereuromark** [comment]
Please read the docs.
Everything of it is relevant for the simple use case which uses this component.

**Comment by othercorey** [comment]
Yes, thanks. Always helpful.

**Comment by dereuromark** [comment]
I am not sure how to document it better to make this clear. It is a bit messy indeed to have both ways. But the plugins are overkill in many situations.
