### ISSUE TITLE
Problem with multipleRoles option on

### ISSUE THREAD

**Issue by menshutin** [dereuromark/cakephp-tinyauth#121]
I'm trying to migrate to cakephp 4.1 from 3.9 and I have an issue with multiple roles.
First, it is not clear from documentation that **multiRole** option (and some other related options) should now be set for **RequestPolicy**. Do I have to duplicate them for **TinyAuth.Authentication** component? 

Ok, at the moment it asks for username, logs him in, and I get an error in ORM caused by this problem:
_Notice (8): Undefined index: id [ROOT/vendor/dereuromark/cakephp-tinyauth/src/Auth/AclTrait.php, line 545]_

It seems to me that with new AuthPlugin data structure that stores logged in user info changed from User entity into Identity class, and AclTrait still expects to find array-like structure with user data. Which is no the case. A made debug($user) in AclTrait and it returns the following structure:
```php
ROOT/vendor/dereuromark/cakephp-tinyauth/src/Auth/AclTrait.php (line 543)
[
'*_accessible' => [ ], 
'*_hidden' => [ ], 
'*_fields' => [
                    'id' => (int) 1, 
                    'active' => true,
                    'name' => 'Anton Menshutin',
                    ...
], 
...
]
```

Because of this error null is passed to ORM and it ends with **Expression is missing operator (IS, IS NOT) with null value.**

**Comment by dereuromark** [comment]
Are you able to provide a PR with suggested changes?

**Comment by menshutin** [comment]
Well, it seems that I can access userid in AclTrait in function `_getUserRoles($user)` with the following code:
`
$user_id=$user["\0*\0_fields"][$this->getConfig('idColumn')];
$roles = $this->_getRolesFromDb($pivotTableName, $user_id);
`
And it seems to work. But accessing user data this way seems like a dirty hack. May be there is a better way? May be we should pass **Identity** to this function, and not the array-like object? In this case user id would be just `Identity->id` which is more natural. But this means changing interface for this function and may be for some others.

**Comment by dereuromark** [comment]
Sure, you can make the pr and we see how we can merge it.

**Comment by dereuromark** [comment]
Is this solved now?

**Comment by menshutin** [comment]
Yes.
