### ISSUE TITLE
AuthPanel in DebugKit is not working

### ISSUE THREAD

**Issue by majaMH** [dereuromark/cakephp-tinyauth#122]
If i add

Configure::write('DebugKit.panels',  ['TinyAuth.Auth' => false]);

for activating the Panel in DebugKit (CakePhp 4, DebugKit4) the whole debugkitPanel collapses...

**Comment by dereuromark** [comment]
Any logged errors? You can open the iframe as own frame, that might tell you more.

**Comment by majaMH** [comment]
Hi Mark,

i don´t know what it was, but now it works... I think there was something cached, or page hadn´t loaded css in full... It works and shows all informations i need... Thanks for tinyauth... i´m not clear with it at all.... but i think it is quite usefull....
