### ISSUE TITLE
How to log in an User

### ISSUE THREAD

**Issue by majaMH** [dereuromark/cakephp-tinyauth#123]
I´ve set up authentication and authorization... Everything with auth_allow.ini and auth_acl.ini works...

On Pages where login is required, User get´s redirected to users/login....

But how to log in Users... Is the login-Process a part of standard Cakephp4 or do i have to do it somehow with tinyauth...

I haven´t found someting in docs for this....

**Comment by dereuromark** [comment]
Yes, everything that is not handled by this plugin is automatically core related.
So normal login procedure.

**Comment by majaMH** [comment]
Ah, ok... i´ll try my best... ;-)

Thanks a lot...

**Comment by dereuromark** [comment]
See also sandbox :) As showcase.

**Comment by majaMH** [comment]
I just downloaded a few minutes ago... ;-)
