### ISSUE TITLE
Problem when using new Cakephp Authentication Plugin

### ISSUE THREAD

**Issue by majaMH** [dereuromark/cakephp-tinyauth#124]
I followed the Instruction to use tinyauth with new Authentication Plugin by cakephp4...

in AppController.php:
$this->loadComponent('TinyAuth.Authentication', []);

in Application.php
use Authentication\Middleware\AuthenticationMiddleware;

inside public function middleware
$middlewareQueue->add(new AuthenticationMiddleware($this));            

On Site following error occurs
Subject must be an instance of Authentication\AuthenticationServiceInterface or Authentication\AuthenticationServiceProviderInterface, App\Application given.

**Comment by dereuromark** [comment]
This looks like a unrelated issue - some developer error with namespaces or alike.
