### ISSUE TITLE
Not getting the latest version with composer

### ISSUE THREAD

**Issue by gi-jones** [dereuromark/cakephp-tinyauth#126]
When I do an install like this:
`composer require dereuromark/cakephp-tinyauth `

The set of files I get generate this error when using the helper:
**TinyAuth.AuthUser helper needs TinyAuth.AuthUser component to function. Please make sure it is loaded in your controller.'**

A bit of research let met to line 146 in src/View/Helper/AuthUserHelper.php which in says:
`if ($authUser === null) {`

But in the version I get with composer the line is:
`if (!$authUser ) {`

I can fix now by requesting dev-master from composer, but I don't completely understand why this happens. I'll be the first to admit that my knowledge of Composer and Packagist is sorely lacking, but shouldn't I be getting the master branch?

**Comment by dereuromark** [comment]
You are looking in the wrong places.
What you describe is not relevant to the issue at hand.

The error message is quite verbose and clear: You need to use the component if you want to use that helper (as the data the helper needs is passed down from it).
If you fix what the error message tells you to fix, the issue will go away by design. This has nothing to do with the code diff you found and looked into more deeply.

**Comment by dereuromark** [comment]
Please check https://github.com/dereuromark/cakephp-tinyauth/releases/tag/3.0.2
The issue you pointed at is a case that can happen with not logged in users, I assume.

**Comment by gi-jones** [comment]
I think that is correct.

But as I tried to say, specifically requesting the dev-master, or manually changing the line to `if ($authUser === null) {` fixes the problem. So I think it's already been adressed. 

The issue seems to be that I'm not getting that version when just requiring the latest version with composer. I need to specifically require the dev-master. But to me it looks like the change is already implemented here.

**Comment by dereuromark** [comment]
Maybe an issue with packagist, the version should be available now there too.

**Comment by gi-jones** [comment]
That did it. Thanks.
