### ISSUE TITLE
Integration with authentication plugin and JWT

### ISSUE THREAD

**Issue by marianodonal** [dereuromark/cakephp-tinyauth#128]
Hi Mark, this is not really an issue but I can't figure out how to use tinyauth with form authentication in web frontend and jwt token based on api. I'm using jwt adding middleware in routes prefixed "/api" but without tinyauth plugin... the idea id to perform authorization in api because there's different user roles.
Could you help me with something that enlightens me to understand how to do it?

**Comment by dereuromark** [comment]
Those shouldn't interfere then, if you attach them only as per routing.

**Comment by marianodonal** [comment]
Yes, i'm using with Auth component in default route and authentication and autorization plugin in /api.
The problem is when I try to use both middleware in routes.

`<?php
use Cake\Http\Middleware\CsrfProtectionMiddleware;
use Cake\Routing\Route\DashedRoute;
use Cake\Routing\RouteBuilder;
//use Cake\Routing\Router;
use Authentication\AuthenticationService;
use Authentication\AuthenticationServiceInterface;
use Authentication\AuthenticationServiceProviderInterface;
use Authentication\Identifier\IdentifierInterface;
use Authentication\Middleware\AuthenticationMiddleware;
use Authorization\AuthorizationService;
use Authorization\AuthorizationServiceInterface;
use Authorization\AuthorizationServiceProviderInterface;
use Authorization\Middleware\AuthorizationMiddleware;
use Authorization\Policy\MapResolver;
//--
use Cake\Http\ServerRequest;
use TinyAuth\Policy\RequestPolicy;

$routes->setRouteClass(DashedRoute::class);

$routes->scope('/', function (RouteBuilder $builder) {
  $authenticate = new AuthenticationService();
  $authenticate->setConfig([
    'unauthenticatedRedirect' => '/account/login',
    'queryParam' => 'redirect',
  ]);
  $fields = [
    IdentifierInterface::CREDENTIAL_USERNAME => 'email',
    IdentifierInterface::CREDENTIAL_PASSWORD => 'password'
  ];
  $authenticate->loadIdentifier('Authentication.Password', [
    'fields' => $fields,
    'resolver' => [
      'className' => 'Authentication.Orm',
      'finder' => 'auth'
    ]
  ]);
  $authenticate->loadAuthenticator('Authentication.Session');
  $authenticate->loadAuthenticator('Authentication.Form', [
    'fields' => $fields,
    'loginUrl' => '/account/login',
  ]);
  //--
  $resolver = new MapResolver();
  $policy = new RequestPolicy([
    'includeAuthentication' => true,
  ]);
  $resolver->map(ServerRequest::class, $policy);
  $authorize = new AuthorizationService($resolver);
  //--
  $builder->registerMiddleware('csrf', new CsrfProtectionMiddleware(['httponly' => true]));
  $builder->registerMiddleware('authenticate', new AuthenticationMiddleware($authenticate));
  $builder->registerMiddleware('authorize', new AuthorizationMiddleware($authorize));
  $builder->applyMiddleware('csrf', 'authenticate', 'authorize');
  //--
  $builder->connect('/', ['controller' => 'Account', 'action' => 'login']);
  //--
  $builder->fallbacks();
});

$routes->prefix('api', function (RouteBuilder $builder) {
  $authenticate = new AuthenticationService();
  $fields = [
    IdentifierInterface::CREDENTIAL_USERNAME => 'email',
    IdentifierInterface::CREDENTIAL_PASSWORD => 'password'
  ];
  $authenticate->loadIdentifier('Authentication.JwtSubject', [
    'resolver' => [
      'className' => 'Authentication.Orm',
      'finder' => 'jwt'
    ]
  ]);
  $authenticate->loadIdentifier('Authentication.Password', [
    'fields' => $fields,
    'resolver' => [
      'className' => 'Authentication.Orm',
      'finder' => 'jwt'
    ]
  ]);
  $authenticate->loadAuthenticator('Authentication.Jwt', [
    'returnPayload' => false
  ]);
  $authenticate->loadAuthenticator('Authentication.Form', [
    'fields' => $fields
  ]);
  //--
  $resolver = new MapResolver();
  $policy = new RequestPolicy([
    'includeAuthentication' => true,
  ]);
  $resolver->map(ServerRequest::class, $policy);
  $authorize = new AuthorizationService($resolver);
  //--
  $builder->registerMiddleware('authenticate', new AuthenticationMiddleware($authenticate));
  $builder->registerMiddleware('authorize', new AuthorizationMiddleware($authorize));
  $builder->applyMiddleware('authenticate', 'authorize');
  //--
  $builder->setExtensions(['json']);
  $builder->resources('Countries');
  $builder->resources('Languages');
  //--
  $builder->fallbacks();
});
`

I'm getting "Not Identity found" only in default route, api works well.

**Comment by marianodonal** [comment]
I think i've made it by changing registerMiddleware between scopes, ie: authenticate_web for web and authenticate_api for api. Thanks!
