### ISSUE TITLE
Incompatibility with CRUD plugin

### ISSUE THREAD

**Issue by gi-jones** [dereuromark/cakephp-tinyauth#129]
I'm trying to use Tinyauth and CRUD together on a Cake 4.x project. But it appears that they the rules defined in both allow and ACL are bybassed any time an action is defined only through CRUD (i.e. no action function in the controller). I am fairly sure that this worked before, so it might have been introduced in the shift to 4.x
Anyway, this could of course be something a bug in CRUD somehow, but I'm not sure how to tell. Any thoughts?

**Comment by dereuromark** [comment]
I am not familar with that plugin.
TinyAuth didn't change much though, and is quite unobtrusive in the way that it just adds to the "whitelist" for certain actions.
So you might have to dig a bit deeper on how the combination here creates problems.

If you find a solution, feel free to also PR that one.
