### ISSUE TITLE
Scoped Prefix Routing Bug

### ISSUE THREAD

**Issue by alanapplyby** [dereuromark/cakephp-tinyauth#131]
There seems to be a bug related to scoped prefix routing.

In my routes.php:

```
$routes->scope('/datatables', ['prefix' => 'api/datatables'], function (RouteBuilder $builder) {
....
}
```

My controller is located in

Controller\Api\Datatables\ListingsController.php

My url is: datatables/listings.json

In my auth_allow.ini I have tried:

```
api/Datatables/Listings = *
Api/Datatables/Listings = *
Datatables/Listings = *
datatables/Listings = *
datatables/listings = *
```
Error received:

```
"message": "You are not authorized to access that location.",
"url": "\/datatables\/listings.json",
```

I have other similar non-prefixed routes setup which work fine with the allow_auth. Seems the allowed actions do not work with scoped prefix routes.

I'm using latest dev-master for the plugin and v4.2 Cake.

**Comment by dereuromark** [comment]
See https://github.com/dereuromark/cakephp-tinyauth/blob/master/docs/Authentication.md#prefix-based-allow and the note about CamelCase style etc.

**Comment by alanapplyby** [comment]
Thanks - I added the following:

```
$this->loadComponent('TinyAuth.Auth', [
            ....
            'allowPrefixes' => [
                'Datatables',
                'Api/Datatables'
            ],
        ]); 
```

But still getting; You are not authorized to access that location.

**Comment by alanapplyby** [comment]
. but the above is making all appi/datatables prefixed routes open and public?

**Comment by dereuromark** [comment]
If the docs are not clear, please make PRs where needed.
But you should not use allowPrefixes as this makes the whole thing public, instead you should use the info to derive to the information on how internal prefix naming works.

`/api/datatables` is the URL representation.
But in Cake4 the internal representation is - as documented - always CamelCase, so `Api/Datatables`.
Therefore, the only way that should be working is  `Api/Datatables/Listings = *` etc.

Cache should be double-checked for clearing if this doesn't work as intended.
