### ISSUE TITLE
Fatal error : Public function getAuthorizationService

### ISSUE THREAD

**Issue by saillmone** [dereuromark/cakephp-tinyauth#132]
Hi, 

I am using Authentification and Authorization plugins (Cakephp 4.1). I followed your instructions [here](https://github.com/dereuromark/cakephp-tinyauth/blob/master/docs/AuthenticationPlugin.md) and [here](https://github.com/dereuromark/cakephp-tinyauth/blob/master/docs/AuthorizationPlugin.md).

I have a problem with the function _getAuthorizationService_ in _Application class_ : 

> Fatal error: Declaration of App\Application::getAuthorizationService(Psr\Http\Message\ServerRequestInterface $request, Psr\Http\Message\ResponseInterface $response) must be compatible with Authorization\AuthorizationServiceProviderInterface::getAuthorizationService(Psr\Http\Message\ServerRequestInterface $request): Authorization\AuthorizationServiceInterface

```
    public function getAuthorizationService(ServerRequestInterface $request, ResponseInterface $response) {
        $map = [
            ServerRequest::class => new RequestPolicy(),
        ];
        $resolver = new MapResolver($map);

        return new AuthorizationService($resolver);
    }
```

Can you help me please ?

**Comment by saillmone** [comment]
With this:
```
    public function getAuthorizationService(ServerRequestInterface $request): AuthorizationServiceInterface
    {
        $map = [
            ServerRequest::class => new RequestPolicy(),
        ];
        $resolver = new MapResolver($map);

        return new AuthorizationService($resolver);
    }
```
Return:

> Error : Authorization\Exception\ForbiddenException

**Comment by dereuromark** [comment]
Did you find out what the issue is?
If there is something wrong, feel free to PR also a fix.
