### ISSUE TITLE
Authorization plugin and TinyAuth together

### ISSUE THREAD

**Issue by mpochopien** [dereuromark/cakephp-tinyauth#135]
Hi,

I think Authorization plugin 2.0 from CakePHP and TinyAuth doesn't play well together. What I mean specifically is AuthUser component. It's using old, deprecated in CakePHP 4.0 Auth component. So, methods such as `hasAccess` or `link` form that component don't work. Despite that, everything seems to work well.

Also, in the documentation there's method `hasRole`. From what I looked into the code, there's no such method anymore. Maybe I missed something.

Am I making something wrong, or maybe there's a chance to fix it?

**Comment by dereuromark** [comment]
I dont think auth component should be used in New approach. Can u use the Adapters directly?
We might have to clarify docs once we solved it.

**Comment by mpochopien** [comment]
Hi, sorry for very long time without any answer.

Yes, `AuthComponent` is deprecated sing CakePHP 4.0, so we can not use it anymore in new approach. The problem lies exactly here:

```
protected function _getUser() {
	return (array)$this->Auth->user();
}
```

It is method from `AuthUserComponent` - it can not be executed, cause `AuthComponent` is not in use anymore.

What do you mean by use adapters directly?

**Comment by dereuromark** [comment]
Yes, you can still use it. deprecated means it wont be in 5.0, but in 4.0 it is still there forever.

We can of course try to find ways to use the auth plugins without any such component. And that should be the future safe way forward, just ignoring that there is an AuthComponent, and directly using the plugins.
