### ISSUE TITLE
auth_allow.ini not parsing route prefix

### ISSUE THREAD

**Issue by marianodonal** [dereuromark/cakephp-tinyauth#138]
Hi Mark, when I try to use prefixed routes to allow routes in the Api prefix, it also allows the same controllers in non-prefixed routes.

ie on auth_allow.ini:
`Api/Countries`
This entry also allows non-prefixed Countries controller.
I cannot figure out the reason for this behavior.

Thanks in advance.

**Comment by dereuromark** [comment]
Can you Show the details? Like URLs and Controller code?

**Comment by marianodonal** [comment]
@dereuromark, have you found anything or do you have any ideas to fix this problem? Thanks in advance

**Comment by dereuromark** [comment]
Are you able to reproduce sth similar with demo actions on the sandbox?
https://github.com/dereuromark/cakephp-sandbox
That would help, as once reproduced it is easy to track down and find the issue or a fix.

**Comment by dereuromark** [comment]
Do u have a fix as well? That would solve the issue?

**Comment by marianodonal** [comment]
This resolves this particular scenario.
Maybe we need to run some tests.
Is there a scenario like plugin key or any other key is not present?

**Comment by marianodonal** [comment]
Another way is to fill missing keys in params before send to "_getAllowRule()".
In AuthenticationComponent.php there is a "_prepareAuthentication()" function, maybe we can fill missing params there before calling _getAllowRule().

This is in line 99 of AuthenticationComponent.php
`$rule = $this->_getAllowRule($this->_registry->getController()->getRequest()->getAttribute('params'));`
change to
```
$params = $this->_registry->getController()->getRequest()->getAttribute('params');
if ( !isset($params['plugin']) ) {
$params['plugin'] = NULL;
}
if ( !isset($params['prefix']) ) {
$params['prefix'] = NULL;
}
$rule = $this->_getAllowRule($params);
```

**Comment by marianodonal** [comment]
And this for _getAllowRule()

```
protected function _getAllowRule(array $params) {
	$rules = $this->_getAllow($this->getConfig('allowFilePath'));
	$allowDefaults = $this->_getAllowDefaultsForCurrentParams($params);

	foreach ($rules as $rule) {
		if ( isset($params['plugin']) && !is_null($params['plugin']) ) {
			if ($params['plugin'] !== $rule['plugin']) {
				continue;
			}
		} else {
			if (!empty($rule['plugin'])) {
				continue;
			}
		}
		if ( isset($params['prefix']) && !is_null($params['prefix']) ) {
			if ($params['prefix'] !== $rule['prefix']) {
				continue;
			}
		} else {
			if (!empty($rule['prefix'])) {
				continue;
			}
		}
		if ($params['controller'] !== $rule['controller']) {
			continue;
		}

		if ($allowDefaults) {
			$rule['allow'] = array_merge($rule['allow'], $allowDefaults);
		}

		return $rule;
	}

	return [
		'allow' => $allowDefaults,
		'deny' => [],
	];
}

```
