### ISSUE TITLE
Read ID of Roles table from config

### ISSUE THREAD

**Issue by mpochopien** [dereuromark/cakephp-tinyauth#143]
Hi, so I came across, not really a bug, but something that would be nice to improve. I know, that CakePHP is based on conventions, but sometimes, as me now, I'm working with already existing database. There's no way to define name of the ID column in Roles table.
```php
	protected function _getRolesFromDb(string $rolesTableKey): array {
		try {
			$rolesTable = TableRegistry::getTableLocator()->get($rolesTableKey);
			$result = $rolesTable->find()->formatResults(function (ResultSetInterface $results) {
				return $results->combine($this->getConfig('aliasColumn'), 'id');
			});
```

Here's that code fragment, that I'm talking about, from `AclTrait.php`.

**Comment by dereuromark** [comment]
Do you want to make a PR?

**Comment by mpochopien** [comment]
Sure, why not. I'll make it then in some free time

**Comment by dereuromark** [comment]
PR welcome, closing until then as this is an edge case
