### ISSUE TITLE
Deprecated warning for using options array in find function

### ISSUE THREAD

**Issue by fef-pbo** [dereuromark/cakephp-tinyauth#146]
using options array in MultiColumnAuthenticate and I think BaseAuthenticate (not tested) leads to deprecated warnings.
![grafik](https://github.com/user-attachments/assets/a5fd8b92-5e09-4854-bbb2-9150946d80c0)

![grafik](https://github.com/user-attachments/assets/3af1fddb-51ee-4452-a338-5cdce820aa53)

**Comment by dereuromark** [comment]
Can you check if https://github.com/dereuromark/cakephp-tinyauth/pull/147 resolves this?
I cannot reproduce it for some reason

**Comment by fef-pbo** [comment]
Works! Thank you very much!

**Comment by dereuromark** [comment]
Released
