### ISSUE TITLE
Simple method to Edit own user account or profile

### ISSUE THREAD

**Issue by adam-je** [dereuromark/cakephp-tinyauth#15]
Is the a simple way to allow a user to edit their own user account? 

Given a case where not a **"normal" user** is *only* allowed to view accounts, but not to create, edit, or delete:

    [Users]
     index = *
     view = *
     add = user-manager, reporting, systems-admin
     edit = user-manager, reporting, systems-admin
     delete = user-manager, reporting, systems-admin
</addr>

Is there a recommended way to allow them to edit their own account, say maybe in *beforeFilter*?

**Comment by dereuromark** [comment]
Yes, this is out of scope of rbac auth, you need to do that on a controller code basis, see the sandbox or the cakefest apps on how this can be done.
Also mentioned a bit @ http://www.dereuromark.de/2011/10/05/common-cakephp-problems-and-solutions/#editing-own-account/profile

**Comment by bravo-kernel** [comment]
:tractor:

**Comment by dereuromark** [comment]
?

**Comment by bravo-kernel** [comment]
That's about the only icon I could find to remind me to `track` this issue, excuse me for polluting :wink:

**Comment by adam-je** [comment]
My working solution after following @dereuromark 's blog:

http://www.dereuromark.de/2011/10/05/common-cakephp-problems-and-solutions/comment-page-1/#comment-147875

**Comment by ptica** [comment]
to check for ownership in delete action etc i use the ORM `get` method that throws an Exception in case a record was not found
```
public function delete($id = null)
{
    $key = $this->Keys->get($id, [
        'conditions' => ['Keys.user_id' => $this->Auth->user('id')],
    ]);

    if ($this->Keys->delete($key)) {
   ...
```
