### ISSUE TITLE
Issue because of debug mode off in app.php

### ISSUE THREAD

**Issue by dipeshcct** [dereuromark/cakephp-tinyauth#16]
Hello,

I am using this plugin in cakephp 3.0.
Issue is there when we change in acl.ini file by add or remove permission. On result there will be not impact but when we enable debug mode on and again test then It will work. So how can I resolve this issue.

**Comment by dereuromark** [comment]
By clearing your persistence cache on any change (e.g. when deploying to your life system) as recommended.
