### ISSUE TITLE
Cannot load TinyAuth bootstrap.php

### ISSUE THREAD

**Issue by anhtuank7c** [dereuromark/cakephp-tinyauth#17]
Dear Dereuromark.

I did use `composer` to install plugin and in my `bootstrap.php` I do load your `TinyAuth` plugin with `bootstrap = true`, but seam wrong folder.

Error as bellow, in fact, your plugin folder is: `TinyAuth` instead of `cakephp-tinyauth`

![wrong folder](https://cloud.githubusercontent.com/assets/3163410/11324932/4dc8519e-9172-11e5-998a-a0e9af569e46.PNG)

**Comment by dereuromark** [comment]
I dont know what you are doing but it will work if done correctly.
Please see http://sandbox3.dereuromark.de/ and the github code for reference (or http://cakefest.dereuromark.de/ ) on how it can be done properly.

**Comment by anhtuank7c** [comment]
Problem is: 
When execute composer command on my existing project: `composer require dereuromark/cakephp-tinyauth:dev-master`, i  got plugin folder like: `vendor/dereuromark/TinyAuth` instead of `vendor/dereuromark/cakephp-tinyauth`.

They looking for `vendor/dereuromark/cakephp-tinyauth`, not `vendor/dereuromark/TinyAuth`

When i try rename folder `TinyAuth` to `cakephp-tinyauth`, and it's working now.

When i create a new cakephp 3 project and do exactly command above, 
`composer require dereuromark/cakephp-tinyauth:dev-master`

The plugin folder now: `vendor/dereuromark/cakephp-tinyauth` and it's work normally.
I don't know why.

**Comment by anhtuank7c** [comment]
I think i found problem.
My reference plugin install more `Installing composer/installers (v1.0.22)`, then when i install `cakephp-tinyauth`, they will get `vendor/dereuromark/TinyAuth` version.

**Comment by anhtuank7c** [comment]
Problem come from this plugin:

```
{
	"name": "trentrichardson/cakephp-scheduler",
	"type": "cakephp-plugin",
	"description": "Makes scheduling tasks in CakePHP much simpler.",
	"keywords": ["cakephp","scheduler","cron job","task"],
	"homepage": "http://github.com/trentrichardson/cakephp-scheduler",
	"license": "MIT",
	"autoload": {
	    "psr-4": {
	        "Scheduler\\": "src"
	    }
	},
	"require": {
		"php": ">=5.3.6",
		"composer/installers": "*"
	},
	"support": {
		"source": "https://github.com/trentrichardson/cakephp-scheduler"
	},
	"extra": {
		"installer-name": "Scheduler"
	}
}
```
