### ISSUE TITLE
Prepare 1.2 release

### ISSUE THREAD

**Issue by dereuromark** [dereuromark/cakephp-tinyauth#19]
1.2 release notes will look like:

---

No constants anymore.
Please make sure you upgrade to the new configs:

- usersTable (no constant anymore)
- userColumn (new, defaults to user_id as it was hardcoded before)

usersTable, pivotTable and rolesTable now support plugin prefixing, e.g.:

    // App
    'rolesTable' => 'Roles',

    // User plugin
    'rolesTable' => 'User.Roles',

---

Anything missing?

We need to adjust the plugin syntax with tests prior to making this new release.

**Comment by bravo-kernel** [comment]
Looks good to me and :+1: for finding/sticking to the plugin syntax, totally missed that

**Comment by dereuromark** [comment]
Anyone time working on that?

**Comment by bravo-kernel** [comment]
Not me unfortunately, totally caught up in work atm

**Comment by dereuromark** [comment]
OK, should be all done. Can you please confirm?
