### ISSUE TITLE
Proposition : split the config file

### ISSUE THREAD

**Issue by mtancoigne** [dereuromark/cakephp-tinyauth#21]
The idea behind the proposition is to have the ability to split the config file (acl.ini) in multiple files: I'd like to be able to create an acl.admin.ini with all admin-related rights, an acl.users.ini with users rights, etc... and when the files are merged, the rights are merged too, so I can have this :

```ini
; File acl.whatever.ini
[Controller1]
action1, action2= someRole

; File acl.whatever2.ini
[Controller1]
action1= someOtherRole

; Merged array:
[Controller1]
action1= someRole, someOtherRole
action2= someRole
```

I did something once with Yaml files, but it should be possible with inis too.

What do you think ?

**Comment by dereuromark** [comment]
I would say that this sounds useful for admin (prefix) vs no prefix etc.
But in general, for the same controller key this is not my preference.
If anyone wants to do that on app level, why not.
I am sure this could be supported to merge all `acl.*ini` files.

**Comment by bravo-kernel** [comment]
Nice suggestion @dereuromark :+1:

**Comment by dereuromark** [comment]
Again; Since cached performance is totally irrelevant ;) Even in debug mode the different won't be noticed I am sure.

**Comment by mtancoigne** [comment]
I saw that as a way to organize the ACLS in a per-group way, instead of a single file with all the controllers, prefixes,...
But i can stay with one file too :smile:

**Comment by dereuromark** [comment]
If you want make a PR to support multi acl file :)

**Comment by mtancoigne** [comment]
It won't be today, but for a 1.3 version, why not ;)

**Comment by dereuromark** [comment]
Do you have more input on this? And where would those files be located from?
App + all plugin config folders?

**Comment by dereuromark** [comment]
Resolved with https://github.com/dereuromark/cakephp-tinyauth/pull/44
