### ISSUE TITLE
Denied authorization redirect loop issue

### ISSUE THREAD

**Issue by clthck** [dereuromark/cakephp-tinyauth#22]
I'm using TinyAuth with following configs in `AppController`.
```php
    'authorize' => [
                'TinyAuth.Tiny' => [
                    'multiRole' => false,
                    'autoClearCache' => Configure::read('debug'),
                    'authorizeByPrefix' => true,
                    'prefixes' => ['admin'],
                ],
            ],
```
If I hit `/users` it works fine after logged in as a non-admin user. With the same user, if I hit `/admin/users` it says like this:
```
This webpage has a redirect loop

ERR_TOO_MANY_REDIRECTS
```
And here's the contents of `acl.ini`
```ini
[Users]
* = user

[admin/Users]
* = admin
```

How can I stop the above error?

**Comment by dereuromark** [comment]
This is probably an issue of your application.
It depends on your redirect setup for Auth component.
You should always redirect away from login if already logged in to the users dashboard.
And so the redirect from /admin comes back to login because wrong role, you would get redirected to dashboard which should always be the final redirect. no loops then.

**Comment by clthck** [comment]
ok. I solved the problem by setting `unauthorizedRedirect` to `false`.
Now I have another question.
I have two `UserController` classes - the normal one and the another one in `src/Controller/Admin`.
What is the proper way to handle login in this case?
I mean, TinyAuth provides a way that it automatically reads the authenticated user's role and sent to the corresponding prefix?

**Comment by bravo-kernel** [comment]
Not sure if this is what you want @clthck but I have an identical setup and have chosen to handle all user authentication logic inside (only) the main UsersController. This way:
- all users authenticate against the main UsersController
- I have access to their auth information in both namespaces

Configured using the `loginAction` configuration like shown below:

```php
'loginAction' => [
    'controller' => 'Users',
    'action' => 'login',
    'prefix' => false // make sub-namespaces use main logic (DRY)
]
```

**Comment by dereuromark** [comment]
Yep, thats how it should be, using prefix=>false.
