### ISSUE TITLE
how can define user id Column for user table?

### ISSUE THREAD

**Issue by saeideng** [dereuromark/cakephp-tinyauth#25]
hi
i need use other column instead of `id`  in user table in `multiRole`
in `multiRole` , userColumn and roleColumn is for pivot Table
and this plugin use `id` of user table for query in
`->where([$this->_config['userColumn'] => $user['id']])`
i can open PR for this new option
are you other idea for resolve it?

**Comment by bravo-kernel** [comment]
Fair enough, what do you think @dereuromark ?

**Comment by dereuromark** [comment]
PR is always welcome.
