### ISSUE TITLE
Messaging for auth failures?

### ISSUE THREAD

**Issue by barrychapman** [dereuromark/cakephp-tinyauth#31]
Is it possible to differentiate the messaging for an auth required vs. access denied message?

   - 'That page requires you to be logged in'
   - 'You do not have permission to access that page'

One comes when you are not logged in, the other is sent when you are logged in but do not a sufficient level to access.

**Comment by dereuromark** [comment]
Of course because only one of them is actually handled by the Plugin. The other is auth component.

**Comment by saeideng** [comment]
you can define one action for that
and set `'unauthorizedRedirect'` for example 
`'unauthorizedRedirect' => ['prefix'=>'admin','controller'=>'users','action'=>'permission']`
and set that action in acl.ini like this
```
[admin/Users]
permission,logout=* ;
```
