### ISSUE TITLE
V2.0 preparation

### ISSUE THREAD

**Issue by dereuromark** [dereuromark/cakephp-tinyauth#37]
- Remove deprecations
- Rename acl.ini to auth_acl.ini to be consistent with auth_allow.ini

//EDIT: Or would anyone prefer this to be more concrete:
- tinyauth_allow.ini
- tinyauth_acl.ini

**Comment by dereuromark** [comment]
Final proposal:

- `auth_allow.ini` is now `tinyauth_allow.ini`
- `acl.ini` is now `tinyauth_acl.ini`

Everyone OK with that?

**Comment by bravo-kernel** [comment]
👍🏼
