### ISSUE TITLE
acl.ini not recognised

### ISSUE THREAD

**Issue by mistaq** [dereuromark/cakephp-tinyauth#41]
After installing the plugin, acl.ini does not appear to be recognised, with none of the role authorisations working. However, auth_allow.ini works fine, with the views listed in that being accessible to everyone. 

For example, in acl.ini, I have the UsersController as such:

```
[Users]
index = admin`
edit, view = user, engineer, admin
* = admin
```

However, when I log in as any type of user (admin or othewise), I'm able to access everything as if I'm an admin. In my AppController, the authorisation section is as follows:

```
'authorize' => [
				'TinyAuth.Tiny' => [
					'filePath' => ROOT . DS . 'config' . DS,
					'file' => 'acl.ini',
					'multiRole' => false,
					'usersTable' => 'users',
					'allowUser' => false,
					'authorizeByPrefix' => false,
					'prefixes' => [],
					'superAdminRole' => null,
					'rolesTable'=>'roles',
					'roleColumn' => 'role_id',
					'idColumn' => 'id',
					'aliasColumn' => 'alias',
					'autoClearCache' => true,
					'adminPrefix' => null
				]
			]
```

The roles are defined using a database format, with a roles table "roles", while the users table "users" has foreign key 'role_id' linked to the 'id' in table "roles".

**Comment by dereuromark** [comment]
Is that a Regression from yesterday? Does the previous Version work?

**Comment by mistaq** [comment]
What do you mean by Regression and Previous Version?

**Comment by dereuromark** [comment]
Exactly. Please try the one before.

**Comment by mistaq** [comment]
Using Composer (or even manually), how do I go about getting version 1.4 (the version prior to the latest)?

I can't seem to find the download button for [version 1.4](https://packagist.org/packages/dereuromark/cakephp-tinyauth#1.4.0).

**Comment by dereuromark** [comment]
Never mind, your symptoms tell me that most likely you didnt hook in the adapter correctly.
You should post your complete callback method where you hook it it.

**Comment by mistaq** [comment]
On the AppController, there are two parts: 

`public function initialize`, and that is where I put `$this->loadComponent('TinyAuth.Auth', ['filePath' => ROOT . DS . 'config' . DS ]);`

as well as `public function beforeFilter(Event $event) {parent::beforeFilter($event);`

Currently, the authorize code is inside `public function initialize`, however before I had it in `public function beforeFilter(Event $event)` Regardless of where I put the authorize code as in the first post, it didn't make a difference.

**Comment by dereuromark** [comment]
Please use 1.5.1 then, as before 1.5.1 it was aclPath.
filePath now works as expected.

**Comment by mistaq** [comment]
Nothing's changed, I moved the authorize code back to `beforeFilter` but it's still letting me as a regular user access sections which I stated in acl.ini that it shouldn't be able to (for example, if I use the URL localhost/project/engineers, which a regular user should not be able to access, it still lets them do so.

**Comment by dereuromark** [comment]
You are overwriting your first config, thus making only auth_allow working, acl is disabled again..
Never do that, always only load a component once!
Also dont try to add TinyAuth.Auth and Auth at the same time, chose one of them.
And I also dont even see the adapter added here. So it cant work, of course.

```
        $this->loadComponent('TinyAuth.Auth', [
            'authenticate' => [
            ],
            ...
        ]);
```
Please see the docs again.

**Comment by mistaq** [comment]
So should I remove the entire section of `$this->loadComponent('TinyAuth.Auth', [
            'authenticate' => [` and everything within from the `initialize` function, given it's already in beforeFilter? Or move everything within (eg. loginAction, loginRedirect) to `beforeFilter`?

**Comment by dereuromark** [comment]
Everything should be in initialize IMO, I will have to fix the docs.

**Comment by LuMAXW3B** [comment]
@dereuromark I suppose some ppl don't understand the process correctly.
When they have the auth_allow.ini & acl.ini file in a Plugin, they need to redefine the filePath for both.
I think this is the main problem atm.

@mistaq here you go the right way:
`use Cake\Core\Plugin;

$this->loadComponent('TinyAuth.Auth', [
    'filePath' =>Plugin::configPath('MyPlugin'),
    'authorize' => [
        'TinyAuth.Tiny' => [
            'superAdmin' => '123456789',
            'filePath' =>Plugin::configPath('MyPlugin'),
        ]
    ]
]);`

**Comment by dereuromark** [comment]
You should not mess with the filepath if possible.
Use the defaults, which will point to your app config.
See the two INI files here? https://github.com/dereuromark/cakefest/tree/3.0/config

**Comment by mistaq** [comment]
@dereuromark
Okay I managed to get it working, thanks  :+1: 

@LuMAXW3B
The issue all along was me doubling up on `$this->loadComponent('TinyAuth.Auth', [` and loading it in both `initialize` and `beforeFilter`. 

Now I just have the issue of my Users index being available publicly. Not sure where the issue is.

**Comment by dereuromark** [comment]
What is your UsersController code for beforeFilter etc?

**Comment by mistaq** [comment]
```
public function beforeFilter(Event $event)
    {
        parent::beforeFilter($event);
        // Allow users to register and logout.
        // You should not add the "login" action to allow list. Doing so would
        // cause problems with normal functioning of AuthComponent.
        $this->Auth->allow(['add', 'logout']);
    } 
```

**Comment by dereuromark** [comment]
That code can be completely moved to the auth_allow file.
But it still should not happen that Users index is public... Sure you dont use an outdated cache version?
Please use the documented autoClearCache config, especially for local dev.

**Comment by mistaq** [comment]
autoClearCache is already set as true in the AppController.

**Comment by dereuromark** [comment]
I have no idea
Can you please compare with cakefest app, which is clearly working fine.
Maybe you find out what the difference is.
We should switch the conversation to IRC as well, unless we have more details here to continue in the bug tracker.
