### ISSUE TITLE
DB backend for ACL management?

### ISSUE THREAD

**Issue by dereuromark** [dereuromark/cakephp-tinyauth#43]
Can we discuss the possibility of having an easy admin backend here to manage the roles via website?

My idea would be to hook into the `_getAcl()` method and also allow reading from the database.
We would need the following table:

auth_acl:
- id
- controller (incl prefix and plugin), e.g. `Posts.admin/Posts`
- actions, e.g. `*`
- roles, e.g. `user,admin`

This would then be cached somehow so the _getAcl() would retrieve a list just like it expects from the INI file. We could even write this INI file upon each DB change.

The backend could have pre-parsed dropdown options of all plugins and their controllers and actions as well as available roles and some basic sanity validation.

Any more feedback here?
I think this would make the plugin suitable for many more use cases.

**Comment by opeadeyomoye** [comment]
How about simply allowing adapters to return a list like `_getAcl()` expects from the INI file?

One of such adapters (with its corresponding DB tables) can be proposed out-of-the-box , but I think it's a good idea to provide a degree of flexibility, so the plugin can be made to fit into new or existing application setups.

**Comment by dereuromark** [comment]
Yes exactly 
We could also provide a TinyauthDb plugin with one adapter.

**Comment by opeadeyomoye** [comment]
I'm not sure what you mean by **plugin** there :slightly_smiling_face: .

But yeah, I had an idea about possible table structures for this:

acl_actions:

- id
- name
- plugin
- prefix
- controller
- action
- extension

And a join table like:

acl_actions_roles

- id
- acl_action_id
- role_id

Something like this can come packaged with TinyAuth, and then devs will be able to create their own adapter should they have a different structure, or an entirely different datasource.

What do you think?

**Comment by bravo-kernel** [comment]
This would be a very welcomed feature. I don't have any suggestions for the technique but making it look (more than) nice should not be overlooked either. 💯

**Comment by dereuromark** [comment]
I think that not everyone would want this, so shipping it with the same plugin might be not ideal.
We could provide a cakephp-tinyauth-backend plugin that has this backend functionality and adapter.
Then people can either install only the current one, or both to have full backend functionality, as well.
What do you think?
Wanna get started on this addon plugin?

**Comment by opeadeyomoye** [comment]
Oh, I see what you mean now @dereuromark .

I also don't think everyone would want the full backend functionality, where they can manage what actions their user roles can perform, in their application. It makes sense that that should be in a separate plugin.

However, I was suggesting that, in *this* plugin, we extend `_getAcl()` to use adapters that return a list like what `acl.ini` is currently parsed to. That way, as an example, devs that do not want the plugin with all the backend functionality can create an adapter that helps them fit *this* plugin into their custom auth setup.

**Comment by dereuromark** [comment]
Cool, this is also fully BC, so we can release this as minor.

**Comment by opeadeyomoye** [comment]
Exactly.

Wanna have a crack at it? Or should I?

**Comment by dereuromark** [comment]
Go ahead. If you want me to open a repo for you, I can do that then.

**Comment by opeadeyomoye** [comment]
Let's start with extending `_getAcl()`, the other plugin would come subsequently.

**Comment by opeadeyomoye** [comment]
@dereuromark see #82 . It allows using custom adapters as discussed.

However, I then noticed how `AuthComponent::_getAuth()` does something similar to `AuthTrait::_getAcl()` by attempting to load universally allowed actions from `auth_allow.ini`.

If it aligns with what you have in mind for this plugin, we could totally allow overwriting how both lists are loaded in one's application, should the user have the data stored in other forms/sources.

**Comment by dereuromark** [comment]
I created https://github.com/dereuromark/cakephp-tinyauth-backend and invited @opeadeyomoye as a collaborator. 
Anyone else who wants to have contribution rights there?

**Comment by dereuromark** [comment]
@opeadeyomoye @ others
Anyone interested in getting things started here?

**Comment by dereuromark** [comment]
https://github.com/dereuromark/cakephp-tinyauth/pull/96 will also make it possible to build a backend for Authentication if desired, or at least provide different ways of providing it.

**Comment by dereuromark** [comment]
I think we need a clear cache function here to be called from other scripts if needed to bust the current cache. 
Or, alternatively a cache warming approach (which would then also be called from deploy scripts maybe). Depends on how slow fetching external data is.

**Comment by dereuromark** [comment]
@opeadeyomoye @bravo-kernel 
Basic draft is in master now: https://github.com/dereuromark/cakephp-tinyauth-backend

Please check it out and give some feedback.
We can continue opening tickets and discussion in other repo then now.
