### ISSUE TITLE
Cannot get user role using  $this->loadComponent('TinyAuth.AuthUser');

### ISSUE THREAD

**Issue by r0boto** [dereuromark/cakephp-tinyauth#47]
Hello, 
I'm using  multiple-roles-per-user model and i stucked on the getting the role of the logged user.

I am able to define roles and log-in with allowed roles. But when i tried to get role using the following code: 
**AppController**
`$this->loadComponent('TinyAuth.AuthUser');`

I always got the following exception:

> TinyAuth.AuthUserComponent could not be found.
> 
> Make sure your plugin was loaded from config/bootstrap.php and Composer is able to autoload its classes, see Loading a plugin and Plugins - autoloading plugin classes

So i cannot use this in any controller to get role:

*_DashboardsController extends AppController *_

`$this->Auth->hasRole('admin') //true / false`

Or any other method to get role. 

when i removed the 

`$this->loadComponent('TinyAuth.AuthUser');`

From the appController i was able to get user info, but not the user role from the related table.

In this case i left only the following config:

```
 $this->loadComponent('TinyAuth.Auth', [
            'authenticate' => [
                'Form' => [
                    'fields' => [
                        'username' => 'email',
                        'password' => 'password'
                    ]
                ]
            ],
            'authorize' => [
                'TinyAuth.Tiny' => [
                    'autoClearCache' => true,
                    'multiRole' => true,
                    'roleColumn' => 'role_id',
                    'rolesTable' => 'Roles',
                    'pivotTable' => 'roles_users',
                    //'roleColumn' => 'role',
                    /*
                    'usersTable' => 'users',
                    'rolesTable' => 'users',
                    'roleColumn' => 'role',
                    'aliasColumn' => 'role',
                    */
                ]
            ],
            'loginRedirect' => [
                'controller' => 'Dashboards',
                'action' => 'index'
            ],
            'unauthorizedRedirect' => [
                'controller' => 'Users',
                'action' => 'restricted'
            ],
        ]);
```

How this could be solved? Documentation seems to be outdated in this case.

Many thanks for any advice.

**Comment by dereuromark** [comment]
First of all, you need to have >= 1.6.0 to get those new things.
And then, you must use 
```php
$this->AuthUser->hasRole('admin')
```

**Comment by r0boto** [comment]
I updated plugin to the latest version. Executed migrations and do everything as is described in the readme (where the implementation process is not described well IMHO). After this i got the following error:

**Missing TinyAuth role id field (Auth.User.role_id) in user session**

**But User model should not to contain the role_id** 

What can be wrong in this case please?

**Comment by dereuromark** [comment]
Why not?
How does your role setup look like in the session? Can you please post?

**Comment by r0boto** [comment]
I found that problem was in the placing the 
```

 'TinyAuth' => [
        'multiRole' => true,
    ],
```

In the app.php. I thought that this configuration directive can be placed in the AppController.php . After the insertion to app.php it is working correctly.

**Comment by dereuromark** [comment]
Yeah: https://github.com/dereuromark/cakephp-tinyauth/tree/master/docs#configuration
