### ISSUE TITLE
Check access for the URL

### ISSUE THREAD

**Issue by LubosRemplik** [dereuromark/cakephp-tinyauth#48]
I am trying to check access for the given URL so I have tried to use AuthUserHelper like this:

AppView
`$this->loadHelper('TinyAdmin.AuthUser');`

Template
`$this->AuthUser->hasAccess(['controller' => 'users', 'action' => 'index'])`

It returns following error
`Missing TinyAuth role id field (Auth.User.role_id) in user session`

I am using multi role, see component settings
```
$this->loadComponent('TinyAuth.Auth', [
    'authError' => false,
    'authenticate' => [
        'Form' => [
            'finder' => 'active',
            'fields' => ['username' => 'email']
        ]
    ],
    'authorize' => [
        'TinyAuth.Tiny' => [
            'multiRole' => true
        ]
    ],
    'loginRedirect' => [
        'controller' => 'Users',
        'action' => 'index',
    ]
]);
```

Any ideas?

**Comment by dereuromark** [comment]
'controller' => 'users' !== 'controller' => 'Users' !
mind your casing

The error, though, says your session is not properly set up.
How does the Auth.User array look like in there?

Also, never set those things on the component, please see the docs overview.
It points out you must better use the configure way, otherwise (and thats your problem) the configs are only set for one component, not for the rest of the code.

**Comment by LubosRemplik** [comment]
Changing users, Users controller naming has no effect.

My Auth.User in session looks like this
```
[
	'id' => (int) 1,
	'email' => 'lubos@example.com',
	'first_name' => 'Luboš',
	'last_name' => 'Remplík',
	'status' => true,
	'created' => object(Cake\I18n\FrozenTime) {

		'time' => '2016-11-01T11:01:29+00:00',
		'timezone' => 'UTC',
		'fixedNowTime' => false
	
	},
	'modified' => object(Cake\I18n\FrozenTime) {

		'time' => '2016-11-10T08:44:40+00:00',
		'timezone' => 'UTC',
		'fixedNowTime' => false
	
	}
]
```

Are you saying that I should rather use bootstrap.php file for configuration instead of setting this with component load?

**Comment by LubosRemplik** [comment]
Ignore my question regards config place, this is pretty clear in doc

> // in your app.php
    'TinyAuth' => [
        'multiRole' => true,
        ...
    ],

**Comment by LubosRemplik** [comment]
Moving config into app.php file helped. Thanks!

**Comment by monsurhoq** [comment]
After updating from 1.6.1 to 1.6.4, I am facing same problem
