### ISSUE TITLE
Multiple Role tables

### ISSUE THREAD

**Issue by btaens** [dereuromark/cakephp-tinyauth#5]
Hello,
Really nice plugin, very useful for the kind of application I'm developing.

Would it be possible to have multiple authorization tables, like, say, a user has both Roles and Rights.
I remember the Cake 2 version had it.

**Comment by dereuromark** [comment]
Yeah I removed that as it wasn't clearly documented or structured.
It was a secret gotcha kind of, that used Rights as a secondary information for ACL like stuff in the code.

Do you have a proposal on what to do?

**Comment by btaens** [comment]
I suppose the simplest would be to have an ``aclTables`` in the configuration options, which would be an array, and then simply iterate through them? Although that might get problematic with id based authentication. Perhaps have seperate acl files for them?

Like:
```php
'authorize' => ['TinyAuth.Tiny' => [
    'autoClearCache' => true,
    'aclConfig' => [
        [
            'aclTable' => 'Roles',
            'aclFile' => 'roles.ini',
            'multiRole' => true,
        ],
        [
            'aclTable' => 'Rights',
            'aclFile' => 'rights.ini',
            'multiRole' => true,
        ],
    ],
]],
```

**Comment by dereuromark** [comment]
I think Rights apply not to the auth, but to specific ACL checks e.g. inside the code etc, and as such are out of scope for a TinyAuth authentication adapter.
This would have to be a separate authorization adapter, but that would need to be written first.
It used to mix both and that was a bad idea.

**Comment by btaens** [comment]
Not necessarily, for example, the app I'm developing has roles based on jobs filled at the company. Certain people however get access to some controllers which fall outside of their filled positions, like Manual Editing rights, these people get access to editing the app's manual.

It doesn't have to be rights either, I'm sure there are many solutions out there that use different types of roles for many exotic solutions. I think it would be a useful feature.

Of course, this does introduce some questions, like do you need both types of roles to access said action, or only one? It might be too much of a hassle.

**Comment by btaens** [comment]
One other, simpler modification though that might be extremely useful is to put the constant based settings in the loadComponent configuration instead. I use a bit of a hack where I want to authenticate based on a role's "label". Like every role has a label column (developer for example has DEV), so I have to define a constant ``define('USER_ROLE_KEY', 'role.label');``. I also don't know how much this works on multiRole setups.

**Comment by dereuromark** [comment]
Closing as out of scope for the time being.
