### ISSUE TITLE
BC & performance issues

### ISSUE THREAD

**Issue by saeideng** [dereuromark/cakephp-tinyauth#52]
hi
i think there are 2 problems

1)BC
removing `public validate `
https://github.com/dereuromark/cakephp-tinyauth/blob/c4ecfd60a0a8883e59d70a99219e4dedb5e3c181/src/Auth/TinyAuthorize.php#L143-L203

2)performance
when we used `AuthUserHelper::hasAccess()` and related `_check()` method
and  `$this->_getUserRoles($user);` within `_check() `
so https://github.com/dereuromark/cakephp-tinyauth/blob/master/src/Auth/AclTrait.php#L385-L390 lines executed every time for every calling `AuthUserHelper::hasAccess()`
i think that makes low performance, for example for creating menu items

before this ,I used
`$userRoles=$table->find()....`
 `validate($userRoles , $request) ` in custom helper 
but now I can not doing that :)

**Comment by dereuromark** [comment]
Are u able to make a pr to fix things?

**Comment by saeideng** [comment]
probably 
but i have not a good idea now 
i need to thinking about it

**Comment by dereuromark** [comment]
Don't worry, as documented it is still there, just a bit more cleaner now as cleanly separated Authorization code (not to be mixed with Authentication) inside its own component:
https://github.com/dereuromark/cakephp-tinyauth/blob/master/src/Controller/Component/AuthUserComponent.php#L49

See the docs on the usage of it.

As for your performance issue, if you use that very same method that is designed for it to be used, I think your issue also resolves itself.

**Comment by dereuromark** [comment]
Can you please check if https://github.com/dereuromark/cakephp-tinyauth/pull/53 resolves your performance issue?

**Comment by saeideng** [comment]
For bc : i not using hasaccess now
i used  custom helper and validate() for resolving performance issue, i can change own cods 
But other people ? Or old programs?

I think i have a idea for this
