### ISSUE TITLE
Missing TinyAuth role id field (Auth.User.role_id) in user session

### ISSUE THREAD

**Issue by zledwon** [dereuromark/cakephp-tinyauth#54]
I get this error when trying to use: $this->AuthUser->hasRole('admin'); in a view.
I would like to use DB roles with multi role option, but I'm not sure I fully understand how TinyAuth works and I did something wrong :/

This is my setup:

`        $this->loadComponent('TinyAuth.Auth', [
            'authorize' => [
                'TinyAuth.Tiny' => [
                    'multiRole' => true,
                    'autoClearCache' => true
                ]
            ],
            'authenticate' => [
                'Form' => [
                    'fields' => [
                        'username' => 'username',
                        'password' => 'password'
                    ]
                ]
            ],
            'loginRedirect' => [
                'controller' => 'Homepage',
                'action' => 'index'
            ],
            'logoutRedirect' => [
                'controller' => 'Homepage',
                'action' => 'index'
            ]
        ]);
`

`; ----------------------------------------------------------
; UsersController
; ----------------------------------------------------------
[Users]
* = admin

[Visits]
* = admin, caller

[Workers]
* = admin, caller

[Groups]
* = admin, caller
`

`CREATE TABLE `roles` (
  `id` int(11) NOT NULL,
  `name` varchar(255) NOT NULL DEFAULT '',
  `description` varchar(255) NOT NULL DEFAULT '',
  `alias` varchar(255) NOT NULL DEFAULT '',
  `created` datetime NOT NULL,
  `modified` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
`

`CREATE TABLE `roles_users` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` int(11) unsigned NOT NULL,
  `role_id` int(11) unsigned NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;`

`CREATE TABLE `users` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `username` varchar(255) NOT NULL,
  `password` varchar(255) NOT NULL,
  `active` tinyint(1) NOT NULL DEFAULT '0',
  `token` varchar(255) DEFAULT NULL,
  `real_name` varchar(255) DEFAULT NULL,
  `created` datetime NOT NULL,
  `modified` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;`

**Comment by dereuromark** [comment]
Whats in your session at that Point?

**Comment by zledwon** [comment]
Looks empty. But maybe I'm not checking it right?
Btw. There is no 'role_id' in Users table, I removed it as it is replaced with 'roles_users' table.

**Comment by dereuromark** [comment]
Then your config needs to be adjusted via app.php. See docs.

**Comment by zledwon** [comment]
There it is:

Config(array)
time1485510395

Auth(array)
User(array)
id2
usernamecaller
active(true)
real_nameAny Caller
created(object)
modified(object)

Flash(array)
auth(array)
0(array)

**Comment by zledwon** [comment]
Auth (array)
   User (array)
       id 2
       username caller
       active (true)
       real_name Any Caller
       created (object)
       modified (object)

**Comment by zledwon** [comment]
@dereuromark Can you point where can I read about adjustments I need to make in app.php?

**Comment by dereuromark** [comment]
https://github.com/dereuromark/cakephp-tinyauth/blob/master/docs/Authorization.md#multi-role
And the configuration below

**Comment by zledwon** [comment]
Yes, I'm reading this docs over and over, but I still don't know how can I influence the content of User in session. I think I got the whole setup exactly as described in the docs.
Would Auth.User.role_id (in session) be an array in case of multiRole=true?

**Comment by dereuromark** [comment]
You might have overseen the part about how the session would need to look like for each case:
https://github.com/dereuromark/cakephp-tinyauth/blob/master/docs/Authorization.md#leverage-session

Note especially the part how you can customize the data being pulled upon login into the session. This way it will look like how it is supposed to be, a nested array of roles under the User key.

**Comment by zledwon** [comment]
Ok, so storing User data in session is obligatory?
The docs suggests that it is optional (for speeding up), but maybe I got it wrong :)

Now, I have a custom findAuth() and all the required data in session.
But I still get the same error: "Missing TinyAuth role id field (Auth.User.role_id) in user session".
There still must be something I'm overseeing...

session data:

Auth (array)
User (array)
--- id2
--- username caller
--- roles (array)
--- --- 0(array)
--- --- --- id 2
--- --- --- name Caller
--- --- --- description call center user
--- --- --- alias caller
--- --- --- created (null)
--- --- --- modified (null)
--- --- --- _joinData(array)
--- --- --- --- id 2
--- --- --- --- user_id 2
--- --- --- --- role_id 2

and my config is:

                'TinyAuth.Tiny' => [
                    'multiRole' => true,
                    'roleColumn' => 'role_id',
                    'userColumn' => 'user_id',
                    'pivotTable' => 'roles_users',
                    'aliasColumn' => 'alias',
                    'rolesTable' => 'Roles',
                    'usersTable' => 'Users',
                    'autoClearCache' => true
                ]

**Comment by dereuromark** [comment]
Your configuration is wrong. Use configure in App.php

**Comment by dereuromark** [comment]
Or where did you Set this config?

**Comment by zledwon** [comment]
Not sure what you mean. I want to use database roles, not Configure based roles.
The config above is in initialize() of AppController:

        $this->loadComponent('TinyAuth.Auth', [
            'authorize' => [
                'TinyAuth.Tiny' => [
                    'multiRole' => true,
                    'roleColumn' => 'role_id',
                    'userColumn' => 'user_id',
                    'pivotTable' => 'roles_users',
                    'aliasColumn' => 'alias',
                    'rolesTable' => 'Roles',
                    'usersTable' => 'Users',
                    'autoClearCache' => true
                ]
            ],
            'authenticate' => [
                'Form' => [
                    'fields' => [
                        'username' => 'username',
                        'password' => 'password'
                    ],
                    'finder' => 'auth'
                ]
            ],
            'loginRedirect' => [
                'controller' => 'Homepage',
                'action' => 'index'
            ],
            'logoutRedirect' => [
                'controller' => 'Homepage',
                'action' => 'index'
            ]
        ]);

**Comment by dereuromark** [comment]
And thats your Problem. Use configure to config it Not passing it to component. There is a Warning about this .

**Comment by zledwon** [comment]
... and it works perfectly! :)
Thanks for help and patience for such a nebbish like myself!

Most of all, thanks for writing TinyAuth! It's awesome and sooo useful!

**Comment by dereuromark** [comment]
;) please help to make docs better.

**Comment by zledwon** [comment]
How about some examples of configuration?
I could send you my case with some descriptions, what where in DB and what in which files.
All grouped in one place, as a kind of check-list to look through (in case of problems).

**Comment by dereuromark** [comment]
Sure feel free also PR any improvements
