### ISSUE TITLE
Mixing with Code has issue with Auth->deny()

### ISSUE THREAD

**Issue by arajcany** [dereuromark/cakephp-tinyauth#55]
Hello.

Documentation specifies that you can mix with code but i have a problem with the following situation:

//previous to TinyAuth...
//in Users Controller beforeFilter I would do something like this
$this->Auth->allow(); //allow all actions
$this->Auth->deny(['update']); //deny just the one action

//with TinyAuth...
//inside the INI file
Users = *
//in Users Controller beforeFilter
$this->Auth->deny(['update']); //deny just the one action

This does not appear to work, unauthenticated users can reach the 'update' action.

**Comment by dereuromark** [comment]
You are probably right, the documentation needs some adjusting.

Most people (incl. me) use whitelisting, and here mixing works for sure.
But for blacklisting that seems to be not true then. I never tried that.
Are you able to provide a bugfix here as PR?

**Comment by arajcany** [comment]
OK, ill give it a shot. I'm new to using Auth. :)

**Comment by dereuromark** [comment]
Thanks! Looking forward to your contribution.

**Comment by dereuromark** [comment]
Could this be reproduced so far? Any idea for a fix?

**Comment by thiagoinnfo** [comment]
My AppController in module Admin -> plugin/Admin

Error Users is not associated with Roles
the relationship are correct


    public function initialize()
    {
        parent::initialize();

        $this->loadComponent('RequestHandler');
        $this->loadComponent('Flash');
        
        $this->loadComponent('Auth', [
                'loginAction' => [
                    'controller' => 'Users',
                    'action' => 'login'
                ],
                'loginRedirect' => [
                    'controller' => 'Users',
                    'action' => 'index'
                ],
                'authError' => 'Did you really think you are allowed to see that?',
                'authenticate' => [
                    'Form' => [
                        'fields' => [
                            'username' => 'email',
                            'password' => 'password'
                        ],
                        'scope' => ['Users.active' => true],
                        'contain' => ['Roles']
                    ]
                ],
                'authorize' => [
                    'TinyAuth.Tiny' => [
                        'roleColumn' => 'role_id',
                        'rolesTable' => 'Roles',
                        'multiRole' => true,
                        'pivotTable' => 'roles_users',
                        'superAdminRole' => null,
                        'authorizeByPrefix' => false,
                        'prefixes' => [],
                        'allowUser' => false,
                        'adminPrefix' => null,
                        'autoClearCache' => true
                    ]
                ]
            ]
        );

        /*
         * Enable the following components for recommended CakePHP security settings.
         * see https://book.cakephp.org/3.0/en/controllers/components/security.html
         */
        //$this->loadComponent('Security');
        //$this->loadComponent('Csrf');
    }
