### ISSUE TITLE
Calling the hasRole method in a ModelTable.php file

### ISSUE THREAD

**Issue by lorro** [dereuromark/cakephp-tinyauth#56]
Hi Mark,

I'm having some problems with the following use case.
In a beforeSave method I would like to check if the logged in user has a specific role. If that's the case I set a specific property in the entity.

```php
if ($customer->isNew() && $this->hasRole(ROLE_AGENT)) {           
    $customer->agent_id = $this->user('id');
 }
```

First I let this Table use the AuthUserTrait which allows me to use the $this->user method which works fine.
Though when I call the hasRole method I get the error that _getUserRoles is an unknown method so I also used the AclTrait. But then I get the error that the Table Class is not associated with _config. So I guess the approach I'm following isn't really the correct one :)

Is there an easy way to have access to this hasRole method in a ModelTable class?

Thanks!

**Comment by dereuromark** [comment]
Using the AclTrait ouside of the controller scope is a violation of concerns.
Models need to stay stateless, thus no session data.
You need to pass in the session data here if you need this - see the Footprint plugin of Awesome list.

You can have a behavior or an event then attached to the model, this can then look for the _footprint data and based on that do sth.
I did recently sth similar with https://github.com/josegonzalez/cakephp-version/pull/26/files

**Comment by lorro** [comment]
Oh I see, thanks for the quick explanation :)
I'll have a look into this.

Greetings
