### ISSUE TITLE
Issue with DB Roles.

### ISSUE THREAD

**Issue by Reflej0** [dereuromark/cakephp-tinyauth#58]
Hi, thanks for your auth plugin. I wanted to query, once configured the table of users, roles and roles_users, how specific that a particular role number has access to a controller or function? Thank you.

**Comment by dereuromark** [comment]
Please follow the documentation or use the forum/slug etc. The docs are quite thorough, and so are the example apps (sandbox, cakefest app etc). 
This is a bug tracker, not a help desk.
