### ISSUE TITLE
Compatible with bootstrap ui?

### ISSUE THREAD

**Issue by mma** [dereuromark/cakephp-tinyauth#61]
Hello,
I'm using this plugin but I can't get the Flash to work with
https://github.com/FriendsOfCake/bootstrap-ui
Bootstrap ui requires
`    $this->loadComponent('Auth', [
            'flash' => [
                'element' => 'error',
                'key' => 'auth'
            ],`

**Comment by dereuromark** [comment]
why? what is the exact issue?
it only uses a high level wrapper access, that should work just fine.

**Comment by mma** [comment]
![image](https://user-images.githubusercontent.com/5292321/28754142-9eef9abc-7548-11e7-9fba-e54115513c87.png)
The flash message is not rendered with bootstrap ui.
`	$this->loadComponent('TinyAuth.Auth', [
			'authorize' => [
				'TinyAuth.Tiny' => [
					'autoClearCache' => true,
					'multiRole' => true,
				],
			],
			'loginAction' => [
				'controller' => 'Users',
				'action' => 'login',
			],
			'flash' => [
                'element' => 'error',
                'key' => 'auth'
            ],
			'authError' => __("You can't acces this."),
			'authenticate' => [
				'Form' => [
					'fields' => ['username' => 'email']
				]
			],	
		'storage' => 'Session',
		]);`

**Comment by dereuromark** [comment]
that is not related to this plugin.

**Comment by dereuromark** [comment]
there is no auth key in core anymore.

**Comment by dereuromark** [comment]
any update from your side?

**Comment by mma** [comment]
What did you mean by 'there is no auth key in core anymore. ' ?
I tried to load the component by:
`
$this->loadComponent('TinyAuth')
`
But it gave me an error

**Comment by dereuromark** [comment]
Why `'element' => 'error', 'key' => 'auth'`?
I am sure this is deprecated, it will all just work out of the box without it. See the sandbox and other apps.

**Comment by mma** [comment]
This plugin works perfectly. I think I should ask here for my issue https://github.com/FriendsOfCake/bootstrap-ui
