### ISSUE TITLE
Stateful and Stateless Auth in a single application

### ISSUE THREAD

**Issue by deanoj** [dereuromark/cakephp-tinyauth#62]
Hi,

I'm struggling to configure TinyAuth to handle both form based stateful authentication (for a user and a web browser) and API stateless authentication (to power a JSON API)

I can get the form based auth working fine, and have confirmed it will call each of Authentication classes in the order defined.

However, when simulating an API request (I'm using POSTMAN rest client here) with Accept/Content-Type headers set, the authentication classes are ignored completely.

Before going any further - is what I am trying to do even possible? Can TinyAuth handle both stateless and stateful for a single application at the same time?

I should also note I am using RequestHandlerComponent to handle my JSON dataviews.

**Comment by bravo-kernel** [comment]
I have used both form and stateless together but only for my API. More strongly, in that case the form authenticate is even required or one would never be able to get a token (see the part about `FormAuthenticate` in the **Notes** list at the end of [this blog paragraph](http://www.bravo-kernel.com/2015/04/how-to-add-jwt-authentication-to-a-cakephp-3-rest-api/#5-Enabling-JWT-Authentication)).
