### ISSUE TITLE
Permission for App Controller Actions

### ISSUE THREAD

**Issue by arun6686** [dereuromark/cakephp-tinyauth#63]
How can add permission for app controller actions. i have tried to add through auth_allow.ini as follows

app/testAction = * 

but it doesn't allows user to access link raises unauthorized error.

**Comment by dereuromark** [comment]
You might misunderstand the concept of AppController. It itself does not exist as controller it only shares with all the concrete ones.
So you need to do this on the concrete level for each action - or you need to set it in the AppController beforeFilter code via $this->allow() manually.

**Comment by dereuromark** [comment]
You could try to make a PR here to allow a syntax here for the AppController allowing.
But not sure this will be a often used feature.
Whitelisting on the global level is usually not a good approach.

**Comment by arun6686** [comment]
thanks  dereuromark
