### ISSUE TITLE
No roles when allowing anonymous

### ISSUE THREAD

**Issue by bravo-kernel** [dereuromark/cakephp-tinyauth#64]
If I understand correctly, when allowing anonymous access (using `auth_allow.ini`):

1. Auth is bypassed
2. the user is therefore not authenticated
3. the user does therefore not have any roles available

However understandable this does seem to make it impossible to support the following scenario:

- single API endpoint `/books`
- the endpoint produces different JSON result based on role:
  - result is limited for anonymous
  - users see a bit more data
  - admins see everything

**The problem here** is
- when I allow anonymous access... no user ever authenticates (no roles available)
- when I enable `*` acl... anonymous users can no longer access the resource

❓  Do you think a solution for the scenario above is even possible?

**Comment by dereuromark** [comment]
Well, first of all: Possible for sure :)

The question is probably more: Is this part of auth (tinyauth), or more specific?
So far this plugin does not contain too much "stateless" auth, which this would probably fall into.
Because for stateful I actually resolved this in the past by "creating" tmp roles on the fly:

    if (!sessionRoles) createGuestRole

:)

For stateless you might want to inject this into the roles provided via header or payload before the actual Auth Middleware or component responsible for auth kicks in.

But this can also be considered somewhat a business logic only issue where you can based on the role (or none) give different data back, no auth needed then.

Not sure what the best approach might be in your case.

**Comment by bravo-kernel** [comment]
Thanks for replying,  any hint on where I would have to place that `sessionRoles` trick?

I am only using Tiny's `authorize` btw, the actual Auth is done by JWT.

```php
    protected function _setupAuth()
    {
        $this->_controller->loadComponent('TinyAuth.Auth', [
            'autoClearCache' => Configure::readOrFail('TinyAuth.clearCache'),
            'storage' => 'Memory', // do not use session
            'checkAuthIn' => 'Controller.initialize', // make user data available in beforeFilter()
            'authenticate' => [
                'Form' => [
                    'fields' => ['username' => 'email', 'password' => 'password']
                ],
                'ADmad/JwtAuth.Jwt' => [
                    'finder' => 'obfuscated',
                    'userModel' => 'Users',
                    'fields' => [
                        'username' => 'id'
                    ],
                    'parameter' => 'token',
                    'queryDatasource' => true // must be true, see docblock
                ]
            ],
            'authorize' => [
                'TinyAuth.Tiny' => [
                    'multiRole' => true,
                    'rolesTable' => 'UserRoles',
                    'roleColumn' => Configure::readOrFail('TinyAuth.roleColumn'),
                    'allowUser' => false,
                    'authorizeByPrefix' => false,
                    'superAdminRole' => null,
                    'autoClearCache' => Configure::readOrFail('TinyAuth.clearCache')
                ]
            ],
            'unauthorizedRedirect' => false,
            'loginAction' => [
                'controller' => 'Users',
                'action' => 'login',
                'prefix' => false // make sub-namespaces use main logic (DRY)
            ]
        ]);
    }
```

**Comment by dereuromark** [comment]
At any time before Auth is actually triggered would work.
e.g.  Middleware or at least initialize() of controller probably.

**Comment by bravo-kernel** [comment]
I think I finally understand what you mean and think my `beforeFilter` could be a good place. The trouble is I can't find any method in the source that allows me to set a role for a user (so I can keep using the component's `roles()`, `hasRole()` etc. methods further on in my app code).

```php
    public function beforeFilter(Event $event)
    {
        parent::beforeFilter($event);

        if (!$this->AuthUser->roles()) {
            // add "Unauthenticated" somewhere so `AuthUser->roles()` will give me "Unauthenticated"
        }
}
```

Any pointer on how to make it available to AuthUser?

**Comment by dereuromark** [comment]
Well, before this part you need to write to the session and add your roles into Auth.User.role_id then.
I will close this we can chat more about this, but this is not related to the plugin itself.

**Comment by bravo-kernel** [comment]
Thanks for the hint and closing is fine, will talk to you in chat some time. 👍
