### ISSUE TITLE
Route access instead of action

### ISSUE THREAD

**Issue by LubosRemplik** [dereuromark/cakephp-tinyauth#69]
Currently you can set what action is controlled in `acl.ini`, e.g. `index`, `view`, `edit`, ... but sometimes you action can be more sophisticated and you need more access control.

For example you have `index` action and you pass first parametr to filter your results, e.g.

```
/users/index/all
/users/index/active
/users/index/blocked
```

And you would like `user` role to have access only to the `/users/index/active`.

Acl ini could look like
```
[Users]
index/all, index/blocked = admin
index/active = user
```

Is that something what could be part of TinyAuth or is this out of the plugin concept?

I don't want to fall into ROW based access, but this is about extended action (route), not about the records itself.

**Comment by dereuromark** [comment]
Then it is too easy and cheap to just use separate actions here. Actions dont cost anything.
I think this is out of scope here.

**Comment by LubosRemplik** [comment]
OK :) you are right, will not make things complicated and will make new action instead :)

Thanks for great plugin
