### ISSUE TITLE
using Auth::hasRole()

### ISSUE THREAD

**Issue by repher** [dereuromark/cakephp-tinyauth#7]
Hi!

I'm just migrating a project from cake2 to cake3 and i wonder why there has been a change to Auth::hasRole(). I used this to check if the current user has the given role like this:
```
Auth::hasRole( ROLE_OFFICE )
```
Now I have to use something like this:
```
Auth::hasRole( ROLE_OFFICE, $this->Auth->user('role_id') )
```
Am I doing something wrong? It seems that i could also check the rights with a simple "==".

Thanks!
Bernhard

**Comment by dereuromark** [comment]
The main reason is that the session is not static access anymore, as such you need to pass it in manually now.

**Comment by dereuromark** [comment]
But if you use the component or helper, it should be done for you, and you can use the same nice wrapping as before: `$this->AuthUser->hasRole()`

**Comment by repher** [comment]
Hello!

Thanks for your answer. I just testet using AuthUser but somethind is wrong.

I put `$this->loadComponent('Tools.AuthUser');` after loading TinyAuth and tried `debug($this->AuthUser->hasRole( ROLE_MEMBER ));` afterwards resulting in `false` when it should be `true`.

In `auth.php` (which i loaded in `bootstrap.php`) is the following defined:
```
define('ROLE_MEMBER', 1);
define('ROLE_OFFICE', 2);

return [
    'Roles' => [
        'office' => ROLE_OFFICE,
        'member' => ROLE_MEMBER,
    ],
];
```
Every definition in `acl.ini` works perfectly.

It seems that there is an error in [AuthUserTrait::roles()](https://github.com/dereuromark/cakephp-tools/blob/master/src/Auth/AuthUserTrait.php#L87). The call to `$roles = $this->user(USER_ROLE_KEY);` returns `null`.  If I replace it for example with `$roles = $this->user('role_id');` it works.

Am I doing something wrong?

Thanks,
Bernhard

**Comment by dereuromark** [comment]
Sure you defined USER_ROLE_KEY?

**Comment by repher** [comment]
Mmmh, I thought this is handled like a linked model and translated somewhere to role_id ...?

**Comment by dereuromark** [comment]
Just define it as you need it in your bootstrap :)

    define('USER_ROLE_KEY', 'role_id')

**Comment by repher** [comment]
It works! Thanks!

I was wondering if you could give me some advice? Using TinyAuth I need to check for ACL rights given in acl.ini. Right now I'm using a custom component llike this:

```
class AclComponent extends Component {
	public function check ( $controllerName, $action, $plugin = null )  {
		$request = new Request();
		$request->addParams( [ 'controller' => $controllerName, 'action' => $action, 'plugin' => $plugin ] );
		return $controller = $this->_registry->getController()->Auth->isAuthorized( null, $request );
	}
}
```
Is this ok? Or is there a better way I'm not seeing ...?

Thanks!

**Comment by dereuromark** [comment]
cool.
Feel free to PR docs adjustments so other people know what to do :)

well, the acl was never intended to be used like this. So if it works, I guess its fine.
There might be refactoring possible that could make it cleaner or easier, though.

**Comment by repher** [comment]
Mmmh. I guess adding this functionality to `TinyAuthorize.php` would be a good idea. What do you think about a wrapper aroung `TinyAuthorize::authorize($user, Request $request)`?
