### ISSUE TITLE
Allow loginRedirect action for all authenticated users

### ISSUE THREAD

**Issue by LubosRemplik** [dereuromark/cakephp-tinyauth#70]
With Auth component you can or use default `loginRedirect`, when you use `'authorize' => 'TinyAuth.Tiny'` you might end up with too many redirect untill you specify `loginRedirect` action in the `acl.ini`. 

Would it be good idea to allow this action for all  authenticated users?

**Comment by dereuromark** [comment]
Those are automatically allowed already by AuthComponent
And this one extends the core one ( https://github.com/dereuromark/cakephp-tinyauth/blob/master/src/Controller/Component/AuthComponent.php#L18 )
So this should already be in there if you use either one of those components.

Whats your use case of using sth different but still the TinyAuth adapter?

**Comment by LubosRemplik** [comment]
It might be just because I am using TInyAuth plugin just for `authorize` and using different one for `authenticate`, see my config

```
        $this->loadComponent('TwoFactorAuth.Auth', [
            'authenticate' => [
                'TwoFactorAuth.Form' => [
                    'fields' => [
                        'username' => 'email',
                        'password' => 'password',
                        'secret' => 'secret',
                    ],
                    'finder' => 'active',
                ],
            ],
            'authorize' => [
                'TinyAuth.Tiny' // see bootstrap.php for config
            ],
            'loginRedirect' => [
                'plugin' => 'admin',
                'controller' => 'Projects',
                'action' => 'index',
            ],
        ]);
```

This might be invalid issue :)

**Comment by dereuromark** [comment]
Sure looks like that TwoFactorAuth component doesnt do it.
But I am hesitant of adding this kind of magic things. The manual one is easy enough IMO:
https://github.com/dereuromark/cakephp-sandbox/blob/3.0/config/auth_allow.ini#L8
