### ISSUE TITLE
Plugin

### ISSUE THREAD

**Issue by thiagoinnfo** [dereuromark/cakephp-tinyauth#76]
Hello!

Create one module "Admin" in "plugins/Admin" tinyauth not work on my module admin.

**Comment by saeideng** [comment]
works for me 
please explain more, or ask you question in slack channel

**Comment by dereuromark** [comment]
Please refer to irc and other help channels, also see available docs and sandbox demo app.

**Comment by thiagoinnfo** [comment]
My AppController in module Admin -> plugin/Admin

Error Users is not associated with Roles
the relationship are correct

public function initialize()
{

    parent::initialize();

    $this->loadComponent('RequestHandler');
    $this->loadComponent('Flash');
    $this->loadComponent('TinyAuth.AuthUser');
    $this->loadComponent('Auth', [
            'loginAction' => [
                'controller' => 'Users',
                'action' => 'login',
                'plugin' => 'Admin'
            ],
            'loginRedirect' => [
                'controller' => 'Users',
                'action' => 'index'
            ],
            'authError' => 'Did you really think you are allowed to see that?',
            'authenticate' => [
                'Form' => [
                    'fields' => [
                        'username' => 'email',
                        'password' => 'password'
                    ],
                    'scope' => ['Users.active' => true],
                    'contain' => ['Roles'],
            
                ]
            ],
            'authorize' => [
                'TinyAuth.Tiny' => [
                    'roleColumn' => 'role_id',
                    'rolesTable' => 'Roles',
                    'multiRole' => true,
                    'pivotTable' => 'roles_users',
                    'superAdminRole' => null,
                    'authorizeByPrefix' => false,
                    'prefixes' => [],
                    'allowUser' => false,
                    'adminPrefix' => null,
                    'autoClearCache' => true
                ]
            ]
        ]
    );

}


}
