### ISSUE TITLE
Missing TinyAuth role id field (Auth.User.role_id) in user session 

### ISSUE THREAD

**Issue by sanjeevdivekar** [dereuromark/cakephp-tinyauth#83]
Hi,

Thanks for this wonderful plugin.

I have successfully implemented Tiny Auth and Authorization with the multiRole facility but whenever I tried to access AuthUser component or Helper it gives 

`Missing TinyAuth role id field (Auth.User.role_id) in user session `

I work around this issue by commenting following code from AclTrait.php file _getUserRoles function.
`		if (!$this->getConfig('multiRole')) {
			if (!array_key_exists($this->getConfig('roleColumn'), $user)) {
				throw new Exception(sprintf('Missing TinyAuth role id field (%s) in user session', 'Auth.User.' . $this->getConfig('roleColumn')));
			}
			if (!isset($user[$this->getConfig('roleColumn')])) {
				return [];
			}
			return $this->_mapped([$user[$this->getConfig('roleColumn')]]);
		}` 

What am I doing wrong?

Regards,

**Comment by dereuromark** [comment]
What is the content of your Auth.User session array?
Most likely you are missing the proper config key to make multi-role possible.
Right now it thinks you are using single role (User.role_id), so make sure you follow docs on multi-role config and what DB find call (=> and therefore session structure) you then need.

**Comment by sanjeevdivekar** [comment]
Hi dereuromark,

Can you help me with https://pastebin.com/2US3WUzW code ?

**Comment by sanjeevdivekar** [comment]
Hi,

Somehow I managed to solve. 
While loading AuthUser component and helper and passed multi-role config

        $this->loadHelper('TinyAuth.AuthUser',[
            'multiRole'=>true,
            'superAdminRole'=>1,
            'pivotTable'=>'roles_users'            
        ]);

        $this->loadComponent('TinyAuth.AuthUser',[
            'multiRole'=>true,
            'superAdminRole'=>1,
            'pivotTable'=>'roles_users'
        ]);

I am using Cakephp 3.6.9

**Comment by dereuromark** [comment]
I recommend using Configure here to avoid having to duplicate the settings across component and helper.
But yeah, otherwise all good then.
Closing question as resolved.
