### ISSUE TITLE
hasAccess not considering auth_allow.ini

### ISSUE THREAD

**Issue by gi-jones** [dereuromark/cakephp-tinyauth#85]
I am trying to create a dynamic menu only showing the links, which the user actually has access to.
Using $this->AuthUser->hasAccess() to do it seems to work for everything actually requiring authorization. But it does not take the setup of auth_allow.ini into acccount, and returns false for anything defined therein.

Is there a good way around this?

**Comment by gi-jones** [comment]
Thanks for getting back to me. I'd like to help, but I'm not really sure what you mean by " PR that reads out that data". Honestly I', still learning the whole GIT thing.
Basically I started out using $this->AuthUser->link() and then to isolate I tested with $this->AuthUser->hasAccess($url) adding the url to Auth_allow.ini but NOT the acl.ini. So the user would in reality have access to the url, but hasAccess still returns false.
If I add the url to acl.ini as well, I get a true, but only as long as a user is actually logged in. But obviosly I need it to do this even if there is no user logged in.

Am I making sense?

**Comment by dereuromark** [comment]
Yes, you are making sense.
I see only one problem: What if a dev puts the allow on the controller via ->allow('action') etc?
Then even then allow.ini file wouldnt help here.
I think that is one of the reasons I might only have used this link/tool for internal (non public) links.

You could make a change request on the repo (PR) which outlines changes that help you fix the issue for you.
But this is not too trivial. I might have to clarify in the docs that this link tool should only be used for internal (non public) URLs in the meantime.

**Comment by gi-jones** [comment]
Yeah, I see the problem with that.
Thinking outside the box here: Would it make sense to be able to define a default user role, assigned to all non-authenticated users? Basically a guest role? Maybe as a configuration thing when loading the component? That way one could simply define all the actions in acl.ini.

**Comment by dereuromark** [comment]
That sounds like a possible workaround.
Only issue: it is redundant info then. But technically it solves your issue.

**Comment by gi-jones** [comment]
Wouldn't it basically make it unnecessary to define auth_allow.ini?

**Comment by dereuromark** [comment]
No, because "allow" goes into Authentication adapters, that is before any Authorization ("acl") happens.
These are separate things. 
You are just hacking it to re-use Authentication info in Authorization as copy-and-paste so to speak.

**Comment by dereuromark** [comment]
I added a note for the meantime: https://github.com/dereuromark/cakephp-tinyauth/commit/5f277d40da2748c09eb3fda13a9e52de67d2839e

**Comment by dereuromark** [comment]
We could add an option "includeAuthentication" into the AuthUser helper, and that would use allow INI file only (if you use controller auth you are on your own anyway).
What do you think?

**Comment by gi-jones** [comment]
I'll give a try and get back to you asap

**Comment by gi-jones** [comment]
Ok, I've made a few modifications now and it seems to work for me. 
I'm sorry to say though, that I am unsure how to submit the changes. Do I need to fork the project (as earlier stated I am still figuring out GIT)?

**Comment by dereuromark** [comment]
Yes, and then making a Pr with ur changes.

**Comment by gi-jones** [comment]
Ok, I think I got it :-) 

https://github.com/dereuromark/cakephp-tinyauth/pull/87

As I said these changes seems to make it work in my scenario. I hope you will have a look though, and tell me what you think.

**Comment by dereuromark** [comment]
Resolved via https://github.com/dereuromark/cakephp-tinyauth/pull/88
