### ISSUE TITLE
Auth Help

### ISSUE THREAD

**Issue by ghost** [dereuromark/cakephp-tinyauth#9]
When in a controller or view how to I check for the current users role?

**Comment by dereuromark** [comment]
You can use the AuthUser helper for example - which is part of the Tools plugin so far still.

**Comment by dereuromark** [comment]
If you want you can move those over and clean them up.
I think they should better be part of the TinyAuth plugin.

**Comment by PennyScripter** [comment]
I wanted to move them over out of the tolls as this is all I need.but didn't quite know how to do it, I am just learning. Can you advise?

**Comment by mtancoigne** [comment]
I'm interested into integrating the component and helper in my project too... What should be the best ? include the files in the plugin or include them in my project ?

**Comment by bravo-kernel** [comment]
Big :+1: for not depending on the Tools plugin.

**Comment by dereuromark** [comment]
I am somewhat undecided where to put the code. 
Currently it is still in Tools, and if people want to use AuthUser component/helper they are free to use that plugin an top, but right now no one forces them :)

**Comment by mtancoigne** [comment]
Sure :)
And it depends on your Shim plugin, so we may have a little work to make it work with TinyAuth without dependencies...

**Comment by dereuromark** [comment]
What do you suggest? A new Auth plugin?

**Comment by mtancoigne** [comment]
My bad, I simply replaced the ``use Shim\Controller\Component\Component;`` with ``use Cake\Controller\Component;`` from AuthUserComponent and it seems to work... i'll dig in

**Comment by mtancoigne** [comment]
@dereuromark Nopefor the new plugin, I like the fact that tinyAuth may have a helper and a component. That would make it a complete tiny auth plugin... 

I currently have a bit of time to give it a look, so i'll keep you updated with my tests

**Comment by bravo-kernel** [comment]
Maybe I was misinterpreting this but I was thinking of (and am in need of) something as simple as a `getUserRoles()` method which, IMHO, feels like it belongs in this plugin.

**Comment by mtancoigne** [comment]
@bravo-kernel +1 for this.

**Comment by bravo-kernel** [comment]
I will step out of this discussion for now since I don't know much about the AuthComponent but if the roles could somehow be auto-added to the user's Auth data that would be even more awesome. gl!

**Comment by dereuromark** [comment]
For now I added https://github.com/dereuromark/cakephp-tinyauth/blob/master/docs/README.md#auth-user-data

**Comment by mtancoigne** [comment]
I can't find a way to pass the userRoles to authComponent from TinyAuthorization, so for now I have almost nothing :/

**Comment by dereuromark** [comment]
What do you mean? They should be read from Auth component in 3.1, see the AuthUserComponent etc.

**Comment by mtancoigne** [comment]
TinyAuthorization is used by authComponent to validate actions. The component/helper/trait from the tools plugins get their data from AuthComponent using ``$this->Auth->user()``, so implementing this is not a big deal... The problem comes from the roles used by TinyAuthorization: they are not passed to AuthComponent and I don't see how I can make it available.

**Comment by bravo-kernel** [comment]
How about starting with just the method and try to add it to Auth later?

**Comment by mtancoigne** [comment]
As I understand, TinyAuthorise is called _via_ the ``validate()`` method in the cake's AuthComponent, which return true or false.
To validate, TinyAuthorize reads the config file(s)/DB and that's all, I didn't find a way to define data from TinyAuthorize to AuthComponent...

**Comment by mtancoigne** [comment]
Maybe, one way would be to split the TinyAuthorize in an utility/component which would read the users roles, and the Authorize part would rely on it... But that means at least two calls : one to validate access, and another to fill the ``Auth->user`` array

**Comment by dereuromark** [comment]
You now have access to the roles in the new AuthHelper.
By using

    $this->Auth->isAuthorized() {
    }

you can display specific links and content only if it is allowed by that role.

**Comment by bravo-kernel** [comment]
@dereuromark I think this issue can be closed as all requested features now seem to be available when using the `AuthUserComponent` inside a controller:

```php
public function initialize()
{
    $this->loadComponent('TinyAuth.AuthUser');
}

public function index()
{
    // get all roles
    pr($this->AuthUser->roles());

   // determine if user has a role (works with both alias string and id argument)
   if ($this->AuthUser->hasRole('users')) {
       pr('user has role');
   }
```

Thanks for implementing 👍

**Comment by dereuromark** [comment]
You're welcome! Thanks for clarifying.
