### ISSUE TITLE
Deny support using `!`?

### ISSUE THREAD

**Issue by dereuromark** [dereuromark/cakephp-tinyauth#94]
Is this something people see as useful to have for Authentication?

tinyauth_allow.ini

```ini
Users = index, view ; Public access to index and view action
Extras.Offers = *, !delete ; All expect delete action are public
```

If not we can close this again

**Comment by saeideng** [comment]
what happened id someone uses :point_down:  ?
```ini
Extras.Offers =!delete,  *
```
  ( change order )

**Comment by dereuromark** [comment]
Something similar could be made possible for Authentication (public access):
```ini
[Groups]
* = admin, user
private = !user
```

**Comment by saeideng** [comment]
is this for Authorization?? or Authentication ??
for authorization this can be very useful , but for Authentication no idea

**Comment by dereuromark** [comment]
Done via https://github.com/dereuromark/cakephp-tinyauth/pull/96

**Comment by saeideng** [comment]
:-1:  to force quotes

**Comment by dereuromark** [comment]
dont use deny then. only needed for this

**Comment by dereuromark** [comment]
do u have a better idea? how we can solve it?
