### ISSUE TITLE
Support for named routes

### ISSUE THREAD

**Issue by lorro** [dereuromark/cakephp-tinyauth#98]
Hi Mark,

Apparently the link method in the AuthUserHelper doesn't support the use of named routes to check if a user should see the link or not? Is that correct?

```php
 <?= $this->AuthUser->link('Change Password', ['_name' => 'admin:account:password']); ?>    
```

doesn't show the link

```php
 <?= $this->AuthUser->link('Change Password', ['action' => 'changePassword']); ?>    
```
does

Should I change all my named routes to array variants or is there a way to overcome this issue?

Thanks!

**Comment by dereuromark** [comment]
What do u propose? The name one can be used if you use your own custom routes instead of the plugin defaults.

**Comment by lorro** [comment]
To be honest, I don't know what you mean with `if you use your own custom routes instead of the plugin defaults.` :)
The TinyAuth plugin doesn't have any routes of its own?

**Comment by dereuromark** [comment]
Sry now I understand what you mean.
You would have to fix up hasAccess() method to use _name if defined and only otherwise fall back to URL array. Then it should work.
Are you able to provide a PR here?

**Comment by saeideng** [comment]
the plugin uses/should uses cake's Router::build()` function  to generate

**Comment by dereuromark** [comment]
PR open.
